[dependencies]
base = "https://github.com/dfinity/motoko-base#70e867e8c4bbb16603788212d2cd87d9ac1f937d"
candb = "https://github.com/vporton/CanDB#no-blob"
nacdb = "https://github.com/vporton/NacDB#proper-calls"
prng = "https://github.com/research-ag/prng#main"
btree = "https://github.com/canscale/StableHeapBTreeMap#v0.3.1"
stable-rbtree = "https://github.com/canscale/StableRBTree#v0.6.1"
stable-buffer = "https://github.com/canscale/StableBuffer#v0.2.0"
stablebuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
map7 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"
sha = "https://github.com/enzoh/motoko-sha#master"
matchers = "https://github.com/kritzcreek/motoko-matchers#master"

[package]
name = "NacDBReorder"
version = "1.0.0"
description = "Reorderable lists in NacDB database"
repository = "https://github.com/vporton/NacDBReorder"
keywords = [ "database", "databases", "order", "reorder" ]
license = "MIT"